# Generated by Django 5.1.2 on 2024-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='votesession',
            name='candidates',
            field=models.ManyToManyField(to='base.candidate'),
        ),
        migrations.DeleteModel(
            name='VoteResult',
        ),
    ]
