# Generated by Django 5.1.2 on 2024-10-11 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vote_created_at_alter_votesession_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='votesession',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='votesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
