# Generated by Django 5.1.2 on 2024-10-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_votesession_description_votesession_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votesession',
            name='candidates',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='VoteSession',
        ),
    ]
