# Generated by Django 5.1.2 on 2024-10-12 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_candidat_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidats',
        ),
        migrations.AddField(
            model_name='candidat',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='base.vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_debut_votes',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_fin_votes',
            field=models.DateTimeField(null=True),
        ),
    ]
